### ISSUE TITLE
Clearly mark observed/applied states for VPCInfos/GatewayPeerings/etc

### ISSUE THREAD

**Issue by Frostman** [githedgehog/fabric#1372]
Some clear "accepted/validated" is important and then "applied" by all GW that supposed to have it provisioned.

```
  conditions:
  - lastTransitionTime: "2025-04-25T06:36:19Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-25T06:36:19Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
```
