### ISSUE TITLE
API for Stateless NAT - Notes

### ISSUE THREAD

**Issue by qmonnet** [githedgehog/fabric#1373]
Here are some notes regarding the API for stateless/static NAT, to indicate that

1. We must have the same number of IP addresses available in the original range (the range the IP belongs to when we receive the packet) and the target range (the range we pick an address from, when doing translation). This is likely well understood.

2. We cannot have any arbitrary combination of CIDRs for each range. Instead, both ranges must have a list of CIDRs of the same size. The reason for that is that we cannot consider the list of CIDRs like a bit pool of IP addresses without restrictions: some of the addresses covered by the CIDRs may be network addresses, or broadcast addresses. The user doesn't necessarily consider network and broadcast addresses when providing a CIDR, but maybe they do, the thing is that we have no idea to tell.

Here's an example mapping in the dataplane's docs for the NAT, that might help understand the issue:

https://github.com/githedgehog/dataplane/pull/335/files#diff-eff3605427e25bfaa822a46a2b6fd3c88c7c590afcc3748c72c31b4de468e228R78-R79

For example, this works:

```yaml
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Peering
metadata:
  name: vpc-1--vpc-2
spec:
  peering:
    vpc-1:
      ips:
        - cidr: 10.1.1.0/24
      as:
        - 192.168.1.0/24
    vpc-2:
      ips:
        - cidr: 10.2.1.0/24
```

This should also work, because each CIDR from ordered list `vpc-1.ips` directly maps to `vpc-1.as` ranges:

```yaml
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Peering
metadata:
  name: vpc-1--vpc-2
spec:
  peering:
    vpc-1:
      ips:
        - cidr: 10.1.1.0/24
        - cidr: 10.1.2.0/24
        - cidr: 10.1.3.0/30
      as:
        - 192.168.1.0/24
        - 192.168.2.0/24
        - 192.168.3.0/30
    vpc-2:
      ips:
        - cidr: 10.2.1.0/24
```

But the following doesn't work, because what if 10.1.2.1 is in fact a broadcast address? We wouldn't have a corresponding mapping to offer from 192.168.2.0/30.

```yaml
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Peering
metadata:
  name: vpc-1--vpc-2
spec:
  peering:
    vpc-1:
      ips:
        - cidr: 10.1.1.0/24
        - cidr: 10.1.2.0/31 # 2 IPs
        - cidr: 10.1.3.0/31 # 2 IPs
      as:
        - 192.168.1.0/24
        - 192.168.2.0/30    # 4 IPs
    vpc-2:
      ips:
        - cidr: 10.2.1.0/24
```

Similarly, this likely doesn't work:

```yaml
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Peering
metadata:
  name: vpc-1--vpc-2
spec:
  peering:
    vpc-1:
      ips:
        - cidr: 10.1.2.0/30
        - cidr: 10.1.1.0/24
      as:
        - 192.168.1.0/24
        - 192.168.2.0/30
    vpc-2:
      ips:
        - cidr: 10.2.1.0/24
```

Because doing arbitrary correlation between unordered CIDRs seems totally hazardous.
