### ISSUE TITLE
gnmi set request failed: rpc error: code = InvalidArgument desc = VNI is already used in VRF

### ISSUE THREAD

**Issue by pau-hedgehog** [githedgehog/fabric#735]
Probably linked to:
- https://github.com/githedgehog/fabric/issues/377
- https://github.com/githedgehog/fabric/issues/628

When running multiple times:
```
./hhfab-hhnet vlab vpcs -f
```

I get:
```
13:52:57 INF Switches status ready="[leaf-02 leaf-03 leaf-04 leaf-05 spine-01 spine-02]" notReady=[leaf-01]                                                                                                                          
13:53:06 ERR setup-vpcs: waiting for switches ready: waiting for switches ready: context deadline exceeded                                                                                                                           
Failed after 1 successful executions 
```

In the affected switch agent log:
```
time=2025-02-05T14:45:47.192Z level=ERROR msg=Failed err="failed to run agent: failed to process agent config from k8s: failed to process agent config loaded from k8s: failed to apply actions: GNMI set request failed: gnmi set request failed: rpc error: code = InvalidArgument desc = VNI is already used in VRF VrfVvpc-04"
```

Version:
```
fabric:
  agent: v0.61.1
  alloy: v1.1.1
  api: v0.61.1
  boot: v0.61.1
  controller: v0.61.1
  ctl: v0.61.1
  dhcpd: v0.61.1
  nos:
    sonic-bcm-base: v4.4.0
    sonic-bcm-campus: v4.4.0
    sonic-bcm-vs: v4.4.0
  onie:
    x86_64-accton_as4630_54npe-r0: v0.1.0
    x86_64-accton_as7326_56x-r0: v0.1.0
    x86_64-accton_as7712_32x-r0: v0.1.0
    x86_64-accton_as7726_32x-r0: v0.1.0
    x86_64-cel_seastone_2-r0: v0.1.0
    x86_64-cel_silverstone-r0: v0.1.0
    x86_64-dellemc_s5232f_c3538-r0: v0.1.0
    x86_64-dellemc_s5248f_c3538-r0: v0.1.0
    x86_64-dellemc_z9332f_d1508-r0: v0.1.0
    x86_64-kvm_x86_64-r0: v0.1.0
  proxy: 1.9.1
  proxyChart: v0.61.1
fabricator:
  api: v0.34.1-5-gd1db916f-dirty-mg1239-pc
  controlISORoot: v4081.2.0-hh2
  controller: v0.34.1-5-gd1db916f-dirty-mg1239-pc
  ctl: v0.34.1-5-gd1db916f-dirty-mg1239-pc
platform:
  certManager: v1.16.2
  k3s: v1.31.1-k3s1
  k9s: v0.32.5
  ntp: v0.0.2
  ntpChart: v0.34.1-5-gd1db916f-dirty-mg1239-pc
  reloader: v1.0.40
  toolbox: latest
  zot: v2.1.1
vlab:
  flatcar: v4081.2.0
  onie: v0.2.0
```
