### ISSUE TITLE
Improve printer columns for CRDs

### ISSUE THREAD

**Issue by Frostman** [githedgehog/fabric#845]
```
- additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      priority: 1
      type: string
```
